# faire attention au passage de TZ par exemple le 2021-03-28 1:50:00 !
# Ne pas oubleir les consignes sur les unité etc..
# Attention en rouge : supprimer les 3 premiers lignes de l'Excel !

library(highcharter)
library(data.table)
library(lubridate)
library(dplyr, warn.conflicts = FALSE)
library(utc)
library(xts)

setwd("P:/3-STAGE/AJO/Plateforme_visualisation/")

Conso <- read.csv2("Enedis_SGE_HDM_A05VF6RP.csv", encoding = "UTF8")
Conso <- Conso[3:nrow(Conso),c(1,2)]
Conso <- data.table(
  Time = as_datetime(substr(Conso[,1],1,25), tz = NULL),
  P_10min = as.numeric(Conso[,2])
)

Conso_ipmvp <- Conso
Conso[,
      kWh_10min := c(NA, # Decalage par rapport a energisme (puissance de 00h00 doit etre affichee au bout de ces 10 minute, a savoir : 00h10)
                     round(Conso$P_10min[1:length(Conso$P_10min)-1]/6000,2)
      )
]
Conso[,Time_1h := paste0(substr(Time,12,13),":00")]
Conso[,Time_10min := substr(Time,12,16)]
Conso[,Time_day := as_date(Time)]
Conso[,Time_month := as_date(Time) - day(Time) + 1]
Conso_ipmvp[,
            kWh_10min := c(# pas de decalage pour ipmvp ;) pr pas engendrer ees problemes en rajotuante des premires ligndes presentants les mois
              round(Conso$P_10min[1:length(Conso$P_10min)]/6000,2)
            )
]

Conso_ipmvp[,Time_1h := paste0(substr(Time,12,13),":00")]

Conso_ipmvp[,Time_10min := substr(Time,12,16)]

Conso_ipmvp[,Time_day := as_date(Time)]

Conso_ipmvp[,Time_month := as_date(Time) - day(Time) + 1]



tooltip_formater <- JS(paste0(
  "
        // correction of aggregated week dates generated by {lubridate::floor_date}
        // In the generating random Data script
        // I want to have on hovering the exact date of the hovered day
        // Not the floor_date Date.
         
        function () {
            function getPointCategoryName(point, dimension) {
              var series = point.series,
              isY = dimension === 'y',
              axis = series[isY ? 'yAxis' : 'xAxis'];
              return axis.categories[point[isY ? 'y' : 'x']];
            }
              var date = getPointCategoryName(this.point, 'y');
              var day = parseInt(date.substring(8,10));
              var month = parseInt(date.substring(5,7)) - 1; // JS begin from 0
              var year = parseInt(date.substring(0,4));
              var date_utc = Date.UTC(year, month, day);
              var date_normal = new Date(date_utc);
              var formated_date = date_normal.toLocaleDateString();
              numero_day = date_normal.getDay();
              if(numero_day===0){
              var day_name = 'Dimanche';
              }
              if(numero_day===1){
              var day_name = 'Lundi';
              }
              if(numero_day===2){
              var day_name = 'Mardi';
              }
              if(numero_day===3){
              var day_name = 'Mercredi';
              }
              if(numero_day===4){
              var day_name = 'Jeudi';
              }
              if(numero_day===5){
              var day_name = 'Vendredi';
              }
              if(numero_day===6){
              var day_name = 'Samedi';
              }
          return day_name + '<b>' + ' ' + formated_date +'</b>' + ' ' + getPointCategoryName(this.point, 'x')  +
          '</b>' +'<br>'+ 'Conso : ' + '<b>' + this.point.value + '<b>';
    }
               ")
)

Yaxis_formater <- JS("function () {
                      var date = this.value;
                      var day = parseInt(date.substring(8,10));
                      var month = parseInt(date.substring(5,7)) - 1; // JS begin from 0
                      var year = parseInt(date.substring(0,4));
                      var date_utc = Date.UTC(year, month, day);
                      var date_normal = new Date(date_utc);
                      numero_day = date_normal.getDay();
                      var day = [ 'Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'];
                      return day[numero_day];
                     }")

Conso %>%
  filter(
    Time_day >= as.Date("2021-03-01") &
      Time_day <= as.Date("2021-03-31")
  ) %>% 
  group_by(Time_1h,Time_day) %>%
  summarize(intensity = sum(kWh_10min, na.rm = T)) %>%
  as.data.table() %>% 
  hchart("heatmap",
         hcaes(x = Time_1h, y = Time_day, value= intensity),
         marginTop = 0,
         marginBottom = 0
  ) %>% 
  hc_yAxis(reversed = T, title = "",
           labels = 
             list(formatter= Yaxis_formater
             )) %>% 
  hc_xAxis(title="") %>% 
  hc_exporting(enabled = TRUE, formAttributes = list(target = '_blank'))  %>%
  hc_legend(
    align= 'right',
    layout= 'vertical',
    margin= 0,
    verticalAlign= 'top',
    y= 25,
    symbolHeight= 320
  ) %>% 
  hc_colorAxis(
    min = 0,
    minColor= '#FFFFFF',
    maxColor= "#07AE6B"
  ) %>%
  hc_tooltip(formatter = tooltip_formater,
             borderWidth = 3.5)




# IPMVP graphe : 


# Month : 

# noter en commentaire que les donnes doivent toutes etre quotidiennes
# Comme c'est summarize : sum, tu peux faire des 0 partout sauf une journée ;)
# Période de référence ne dois pas comporter deux 
# A noter : Respecterle nom d e colonne "Date" pour le DT_X_ref
# S'il manque des mois, les rajouter directement dans le excel de base de conso (en respectant la forme ;))
# préferer un seul excel avec période de référence en haut + période de suivi en bas
# Préciser qu'il faut modéliser avec 3 mois minimum si non:
# faux modeles
# non fonctionnement du script
# Mettre en place l'équation qui permet de remplacer des lignes de nouveau lignes de consommations
# qui consiste uniquement à diviser par 6 le nombrre en W

# a supprimer
date_debut_reference <- as.Date("2020-10-01")
date_fin_reference <- as.Date("2021-02-28")
date_debut_suivi <- as.Date("2021-03-01")
date_fin_suivi <- as.Date("2021-05-30")
APE_date_1 = as.Date("2021-03-01")
APE_date_2 = as.Date("2021-04-01")
APE_date_3 = as.Date("2021-05-01")
APE_1 = "Sensibilisation"
APE_2 = "Isolation"
APE_3 = "Changement de chaufferie"










